### ISSUE TITLE
Change color for the data points and export in Jpeg or tiff

### ISSUE THREAD

**Issue by akulan1** [JEFworks/tsne-online#3]
Hi,

Thank you very much for making tSNE online. It is a wonderful program. Is it possible to change the color of the data points and also export as a Jpeg, tiff or pdf for publication purposes.

Thank you very much.

Regards,
Nirmala

**Comment by JEFworks** [comment]
Hi Nirmala,

I added an export button in commit 663922b to help address this issue. You can now export the tSNE plot as an SVG. You will be able to easily modify colors as well as convert to Jpeg, tiff, or pdf using Adobe Illustrator or other vector image editing software and thus I will not be supporting these functionalities in tsne-online. 

Hope this works for you!

Best,
Jean

**Comment by akulan1** [comment]
Thank you sooooo  much Jean for your help.

Regards,
Nirmala

---------------------------------------------------------------------
Dr. Nirmala Akula
Building 35, Room 1A-100
35 Convent Drive
Human Genetics Branch
National Institute of Mental Health
National Institutes of Health
Bethesda, MD 20892-3719
Phone# 301-451-4258
